### ISSUE TITLE
NPM module requires global babel dependencies to function

### ISSUE THREAD

**Issue by shawnHartsell** [LeanKit-Labs/tag-release#23]
After installing via ```npm install -g tag-release``` and running the module, I immediately got a nasty stack trace about missing babel dependencies (sorry, I overwrote the original stack). As soon as I installed the dependencies I was missing (babel-templates, babel-types) the module functioned as expected.

I think we can provide a better user experience if we don't expect users/environments to have these global dependencies present. One idea I had is to add a npm script to transpile the code (after linting, etc) and then publishing that to NPM

I'm happy to make a PR if others think this is a good idea :)

**Comment by elijahmanor** [comment]
Hmm, that is strange. Geoff did a fresh install on his Linux VM and didn't have any issues. He did need to switch to Node v5, but that was about it. I installed another version of Node and didn't need to install any global dependencies outside of tag-release. So, I'm not sure exactly what is going on with your environment. What version of node and npm were you using?

**Comment by shawnHartsell** [comment]
atm I'm on v6

**Comment by elijahmanor** [comment]
@shawnHartsell I saw the same warning when installing on windows yesterday. The problem dependency was something only needed for testing so I moved it to a devDependency and added a `test` environment that will pull in the module as during development. This is associated with PR #28 that fixes a windows bug we saw a couple days ago. Hopefully this will address the issue you saw
