### ISSUE TITLE
Problem getting git commit history on Windows

### ISSUE THREAD

**Issue by GeoffCraig** [LeanKit-Labs/tag-release#35]
With the latest version on Windows it always asks for GitHub credentials and it always comes back with undefined for the git log.

**Comment by ryexley** [comment]
Yo @GeoffCraig...couple things on this. First of all, there was a new release of tag-release pushed out very recently, so you should try updating to that.

Second, and perhaps most important, what protocol are you using for git, SSH or HTTPS? I was originally setup with HTTPS, and had a lot of problems with the Git Credential Manager for Windows _actually_ caching and using my credentials. I reconfigured git to use SSH, and it started actually using the credentials cached in my `.gitconfig` file, and everything started working just fine. Have you tried anything like that? If not, please do, and let us know if that helps at all.

Thanks Geoff.

**Comment by elijahmanor** [comment]
I tested this today and the latest version seems to work great. If there are any specific windows issues, we can open a new issue with details and proceed.
