### ISSUE TITLE
Add to `--reset` flag ability to verify an upstream remote exists

### ISSUE THREAD

**Issue by elijahmanor** [LeanKit-Labs/tag-release#45]
Another common issue tag-release users run into is not having an upstream setup. It would be nice if `--reset` would detect the upstream remote and if one isn't present clippy could let the user know and how to set it up

**Comment by elijahmanor** [comment]
You might be able to use the `https://developer.github.com/v3/repos/#get` endpoint from the `github-api` repo already in `tag-release` http://github-tools.github.io/github/docs/2.3.0/Repository.html#getDetails

**Comment by RobertReaves** [comment]
This was resolved with https://github.com/LeanKit-Labs/tag-release/pull/93
