### ISSUE TITLE
The pre-release feature shouldn't update the CHANGELOG.md

### ISSUE THREAD

**Issue by elijahmanor** [LeanKit-Labs/tag-release#48]
The pre-release feature should not update the `CHANGELOG.md` with the logs, but it should still pass along the logs to the tag and github release.

Currently this is problematic when moving code from a pre-release into a legitimate release since it causes rebase merging conflicts. The logs from the pre-release will get added to the `CHANGELOG.md` when an official release happens, so those are not lost.

**Comment by RobertReaves** [comment]
This should have been addressed in v5.1.0
