### ISSUE TITLE
Make tag-release help promote a prerelease to a normal release

### ISSUE THREAD

**Issue by elijahmanor** [LeanKit-Labs/tag-release#49]
Notes from @dcneiner in slack...

> For promoting the component project:
> 1. Rebase master of that project into your branch
> 2. Drop any commits that bumped the version/changelog
> 3. Merge into master with `--no-ff` so you get a merge commit
> 4. Tag release that project as normal

So, here is what we are thinking at this point...

`tag-release --promote thisisthetag`

OR

```
tag-release --promote
> o tag-1
> x tag-2
> o tag-3
```

0. `git fetch upstream`
1. make branch based off provided or selected tag
2. remove silly prerelease commit (which removes package.json & changelog.md)
3. `rebase upstream/master` into it to get latest (this may cause user conflicts to resolve)
4. either `tag-release --continue` or run `tag-release --promote` again (temp branch `promote-release-v<tag>`)
5. merge into master with `--no-ff`
6. do normal `tag-release` things

NOTE: If the user has multiple `promote-release-v<tag>` branches, then ask them which one to continue

NOTE: Update the `--reset` flag to delete any in-progress promotion branches

**Comment by elijahmanor** [comment]
Notes from @dcneiner in slack...

> For promoting the component project:
> 1. Rebase master of that project into your branch
> 2. Drop any commits that bumped the version/changelog
> 3. Merge into master with `--no-ff` so you get a merge commit
> 4. Tag release that project as normal

> For promoting the lightning branch:
> 1. Rebase lightning master into your branch
> 2. Update package.json to point to the final version of your component
> 3. Squash the lightning package.json change commits down to a single commit that says something like "Bumped [project name] to [version] to pull in [change]"
> 4. Force push that to the same upstream branch that went through QA
> 5. Open your PR to develop for Ops (edited)

**Comment by RobertReaves** [comment]
This should now be a feature as of v5.1.0
