### ISSUE TITLE
Use regex to remove pre-release commits

### ISSUE THREAD

**Issue by RobertReaves** [LeanKit-Labs/tag-release#86]
Currently, whenever we use the --promote feature we selectively remove pre-release commits based on if they contain the "tag" or "identifier" along with the version they were created with. This can be problematic if a pre-release is based off another pre-release or if the pre-release is retagged with another "identifier".

Example:
5.8.0-new.1
5.8.0-new.0
5.7.0-new.0

tag: 5.8.0-new

So, this would remove the "5.8.0-new.0" and "5.8.0-new.1" commit. We would also want it to remove the "5.7.0-new.0" commit. This situation could happen from someone rebasing the branch with upstream/master and repre-releasing in with the bumped version.

We need to update the "generateRebaseCommitLog" to use a regex to find all the pre-release commits no matter what the "tag" or "identifier" and version.

**Comment by elijahmanor** [comment]
PR #89 fixed this
